image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - "%APPDATA%\npm"

init:

install:
  - choco install nodejs --version=9.10.0
  - npm install -g lumo-cljs clob
  - npm install

build_script:
  - npm run test-windows

test: off
