#!/usr/bin/env bash

set -eo pipefail

jar=${1:-target/clob-uber.jar}

rm -rf classes
mkdir classes
clojure -X:deps prep
clojure -A:jansi -Spom
clojure -M:jansi:depstar -m hf.depstar.uberjar --compile -m clob.frontend.rebel "$jar" # --verbose
