#!/usr/bin/env bash

set -eo pipefail

jar=${1:-target/clob-sci.jar}

export __CLOB_USE_SCI_EVAL__=true

rm -rf classes
mkdir classes
clojure -Msci -e "(compile 'clob.readline.line-reader-class)"
clojure -Asci -Spom
clojure -M:depstar:sci -m hf.depstar.uberjar --compile -m clob.frontend.sci-rebel "$jar" # --verbose
