#!/bin/bash
set -e
cd babashka/
export BABASHKA_FEATURE_CLOB=true
export BABASHKA_JAR=clob
./script/uberjar
./script/compile
./clob --describe
# this doesn't seem to work
#./clob -m clob.frontend.rebel
